//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pubcrew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amenity
    {
        public int amenityId { get; set; }
        public string supplyName { get; set; }
        public string amProductLineName { get; set; }
        public int locationId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
